# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TyPkMHoAxr7-clN9lFXff-JRBNCLWg66
"""

from google.colab import files
uploaded = files.upload()
import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded["DataSet2.csv"]))

df

import numpy as np
attribute =np.array(df)[:,:-1]
target=np.array(df)[:,-1]

num_attribute=len(attribute[0])
specific_hypothesis=[0]*num_attribute

specific_hypothesis

range(len(target))

for i in range(len(target)):
  if target[i]=="yes":# if i sample has yes 
     specific_hypothesis=attribute[i,:]
     index_yes=i
     break
  else:
     continue

for z in range(i+1,len(attribute)):
   if target[z]=="yes":
         vector_sample=attribute[z,:]
         for k in range(len(attribute[0])):
            if vector_sample[k]!=specific_hypothesis[k]:
               specific_hypothesis[k]="?"
            else:
                continue
   else:
       continue

print(specific_hypothesis)